name: Main

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  main:
    name: Main Process
    runs-on: ubuntu-slim
    env:
      GO_VERSION: 1.24
      GOLANGCI_LINT_VERSION: v2.7.1
      YAEGI_VERSION: v0.16.1
      CGO_ENABLED: 1
    
    steps:

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # https://golangci-lint.run/usage/install#other-ci
      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Install Yaegi ${{ env.YAEGI_VERSION }}
        run: curl -sfL https://raw.githubusercontent.com/traefik/yaegi/master/install.sh | bash -s -- -b $(go env GOPATH)/bin ${YAEGI_VERSION}

      - name: Check and get dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod
          # git diff --exit-code go.sum
          go mod download
          go mod vendor
          # git diff --exit-code ./vendor/

      - name: Lint and Tests
        run: make

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

      - name: Run tests with Yaegi
        run: make yaegi_test
        env:
          GOPATH: ${{ github.workspace }}/go
